---
- name: jenkins-master.yml
  hosts: localhost
  become: True
  become_user: root
  tasks:

    - name: httpd(apache2) docker pip and ssl
      apt:
        pkg:
          - apache2
          - docker.io
          - python-pip
          - ssl-cert
        state: latest
        update_cache: yes
      retries: 6
      delay: 20
      register: packages_install
      until: packages_install is not failed

    - name: install docker python package for ansible
      pip:
        executable: /usr/bin/pip
        name: docker

    - name: enable / start docker
      systemd:
        name: docker
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Docker Volume (db)
      docker_volume:
        name: jenkinsvol_master

    - name: Docker Network
      docker_network:
        name: jenkinsnet
        ipam_config:
          - subnet: "{{ jenkinsnet_cidr }}"

    - name: Docker Container - jenkins master
      docker_container:
        name: jenkins_master
        image: jenkins/jenkins:lts
        networks:
          - name: jenkinsnet
            ipv4_address: "{{ jenkinsnet_master }}"
        ports:
          - "127.0.0.1:{{ jenkinsmaster_webport }}:8080"
        restart_policy: "always"
        volumes:
          - jenkinsvol_master:/var/jenkins_home

    - name: Enable Apache2 Modules for proxy and ssl
      apache2_module:
        name: "{{ item }}"
        state: present
      with_items:
        - headers
        - proxy
        - proxy_http
        - ssl
      register: apache_modules

    - name: Proxy Configuration for Apache
      template:
        src: jenkins-web-proxy.conf
        dest: /etc/apache2/sites-enabled/jenkins-web-proxy.conf
        owner: root
        group: root
        mode: 0444
      register: proxy_conf

    - name: Apache2 Enabled / Restarted
      systemd:
        name: apache2
        state: restarted
        enabled: yes
      when: apache_modules.changed or proxy_conf.changed
