---
- name: jenkins-master.yml
  hosts: localhost
  become: True
  become_user: root
  tasks:

    - name: docker pip3 and ssl
      apt:
        pkg:
          - docker.io
          - python3-pip
          - ssl-cert
        state: latest
        update_cache: yes
      retries: 6
      delay: 10
      register: packages_install
      until: packages_install is not failed

    - name: various container directories
      file:
        path: "{{ item }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0750
      with_items:
        - /opt/jenkins
        - /opt/webproxy

    - name: secure proxy to pihole confs
      template:
        src: "{{ item }}"
        dest: "/opt/webproxy/{{ item }}"
        owner: ubuntu
        group: ubuntu
        mode: 0444
      with_items:
        - httpd-ssl.conf
        - httpd.conf

    - name: install docker python package for ansible
      pip:
        executable: /usr/bin/pip3
        name: docker

    - name: enable / start docker
      systemd:
        name: docker
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Jenkins Dockerfile
      blockinfile:
        create: yes
        path: /opt/jenkins/Dockerfile
        mode: '0644'
        owner: ubuntu
        group: ubuntu
        block: |
          FROM jenkins/jenkins:slim
          USER root
          RUN apt-get update && \
              DEBIAN_FRONTEND=noninteractive apt-get install -y openssl curl wget && \
              DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
          USER jenkins
      register: jenkins_dockerfile

    - name: Jenkins docker image
      docker_image:
        name: jenkins_custom
        build:
          path: /opt/jenkins
        source: build
        force_source: yes
      when: jenkins_dockerfile.changed

    - name: Docker Network
      docker_network:
        name: jenkinsnet
        driver: bridge
        ipam_config:
          - subnet: "{{ docker_network }}/24"
            gateway: "{{ docker_gw }}"

    - name: Docker Container - jenkins master
      docker_container:
        name: jenkins_master
        hostname: jenkins-master
        image: jenkins_custom
        networks:
          - name: jenkinsnet
            ipv4_address: "{{ docker_jenkinsmaster }}"
        restart_policy: "always"
        purge_networks: yes
        volumes:
          - /opt/jenkins:/var/jenkins_home:rw

    - name: Docker Container - web proxy
      docker_container:
        name: web_proxy
        hostname: web-proxy
        image: httpd:2.4
        networks:
          - name: jenkinsnet
            ipv4_address: "{{ docker_webproxy }}"
        ports:
          - "443:443"
        volumes:
          - /opt/webproxy/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf:ro
          - /opt/webproxy/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
          - /etc/ssl/certs/ssl-cert-snakeoil.pem:/usr/local/apache2/conf/server.crt:ro
          - /etc/ssl/private/ssl-cert-snakeoil.key:/usr/local/apache2/conf/server.key:ro
        purge_networks: yes
        restart_policy: "always"
